data:
    name: multiview_homographies
    data_dir: revisitop1m
    train_size: 150000
    val_size: 2000
    batch_size: 32
    num_workers: 16
    homography:
        difficulty: 0.7
        max_angle: 45
    photometric:
        name: lg
model:
    name: multiview_pipeline
    extractor:
        name: third_party.superpoint
        max_num_keypoints: 512
        force_num_keypoints: True
        detection_threshold: 0.0
        nms_radius: 3
        trainable: False
    ground_truth:
        name: multiview_matchers.multiview_homography_matcher
        th_positive: 3
        th_negative: 3
    multiview_matcher:
        name: multiview_matchers.par_comatcher_no_pri
        flash: false
        checkpointed: true
train:
    seed: 0
    epochs: 40
    log_every_iter: 100
    eval_every_iter: 1500
    lr: 1e-4
    lr_schedule:
        start: 20
        type: exp
        on_epoch: true
        exp_div_10: 10
    plot: [5, 'src.visualization.visualize_batch.multiview_make_match_figures']
benchmarks:
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5