name: comatcher
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.6.2=py310h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - curl=8.7.1=hdbd6064_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gdbm=1.18=hd4cb3f1_4
  - gettext=0.21.0=h39681ba_1
  - git=2.40.1=pl5340h9abc3c3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.10.0.4=0
  - libcurand=10.3.6.39=0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxml2=2.10.4=hfdd30dd_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.14=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - perl=5.34.0=h5eee18b_2
  - pillow=10.3.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - pytorch=2.3.1=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=py310h06a4308_0
  - setuptools=69.5.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.3.1=py310_cu121
  - torchtriton=2.3.1=py310
  - torchvision=0.18.1=py310_cu121
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.1=py310h06a4308_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - albucore==0.0.11
      - albumentations==1.4.10
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - bracex==2.5.post1
      - build==1.2.2.post1
      - clarabel==0.9.0
      - click==8.1.8
      - contourpy==1.2.1
      - cvxpy==1.6.0
      - cycler==0.12.1
      - deeplsd==0.0
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.7
      - ffmpy==0.5.0
      - fonttools==4.53.0
      - freetype-py==2.5.1
      - fsspec==2024.6.0
      - gluefactory==0.0
      - gradio==5.13.1
      - gradio-client==1.6.0
      - grpcio==1.64.1
      - h11==0.14.0
      - h5py==3.11.0
      - homography-est==0.0.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - imageio==2.34.1
      - joblib==1.4.2
      - kapture==1.1.10
      - kapture-localization==1.1.10
      - kiwisolver==1.4.5
      - kornia==0.7.2
      - kornia-moons==0.2.9
      - kornia-rs==0.1.3
      - lazy-loader==0.4
      - lightglue==0.0
      - llvmlite==0.44.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - numba==0.61.0
      - numpy-quaternion==2024.0.3
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - orjson==3.10.15
      - osqp==0.6.7.post3
      - packaging==24.1
      - pandas==2.2.2
      - piexif==1.1.3
      - pillow-heif==0.21.0
      - pip==21.3.1
      - poselib==2.0.1
      - protobuf==4.25.3
      - pycolmap==3.10.0
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pydub==0.25.1
      - pyglet==1.5.31
      - pygments==2.19.1
      - pyopengl==3.1.0
      - pyparsing==3.1.2
      - pyproject-hooks==1.2.0
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytlsd==0.0.4
      - pytz==2024.1
      - qdldl==0.1.7.post5
      - rich==13.9.4
      - roma==1.5.1
      - ruff==0.9.3
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scikit-image==0.24.0
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - starlette==0.45.3
      - tabulate==0.9.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tifffile==2024.6.18
      - tomli==2.0.1
      - tomlkit==0.13.2
      - tqdm==4.66.4
      - trimesh==4.6.0
      - typer==0.15.1
      - tzdata==2024.1
      - uvicorn==0.34.0
      - wcmatch==10.0
      - websockets==14.2
      - werkzeug==3.0.3
