model:
    name: two_view_pipeline
    extractor:
      name: third_party.superpoint
      max_num_keypoints: 2048
      detection_threshold: 0.0
      nms_radius: 3
    matcher:
      name: matchers.lightglue_pretrained
      features: superpoint
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
benchmarks:
    megadepth4500:
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      model:
        extractor:
          max_num_keypoints: 512  # overwrite config above